default_platform(:android)

platform :android do
  desc "Build APK. Accepts build_type option (default: Debug). Keystore is only used for Release builds."
  lane :build do |options|
    build_type = (options[:build_type] || "Debug").capitalize

    gradle_options = {
      task: "assemble",
      build_type: build_type,
      flags: "--stacktrace",
      print_command: false,
    }

    if build_type == "Release"
      gradle_options[:properties] = {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"],
      }
    end

    gradle(**gradle_options)
  end
end
